//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutorizaceDigitalnihoUkonu.Web.SubmissionService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.government-gateway.cz/wcf/submission")]
    public partial class GGErrorException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime gatewayTimeStampField;
        
        private bool gatewayTimeStampFieldSpecified;
        
        private string locationField;
        
        private int numberField;
        
        private bool numberFieldSpecified;
        
        private string raisedByField;
        
        private string textField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime GatewayTimeStamp {
            get {
                return this.gatewayTimeStampField;
            }
            set {
                this.gatewayTimeStampField = value;
                this.RaisePropertyChanged("GatewayTimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GatewayTimeStampSpecified {
            get {
                return this.gatewayTimeStampFieldSpecified;
            }
            set {
                this.gatewayTimeStampFieldSpecified = value;
                this.RaisePropertyChanged("GatewayTimeStampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberSpecified {
            get {
                return this.numberFieldSpecified;
            }
            set {
                this.numberFieldSpecified = value;
                this.RaisePropertyChanged("NumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string RaisedBy {
            get {
                return this.raisedByField;
            }
            set {
                this.raisedByField = value;
                this.RaisePropertyChanged("RaisedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.government-gateway.cz/wcf/submission")]
    public partial class Checkpoint : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string serverField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Server {
            get {
                return this.serverField;
            }
            set {
                this.serverField = value;
                this.RaisePropertyChanged("Server");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("Timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
                this.RaisePropertyChanged("TimestampSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.government-gateway.cz/wcf/submission")]
    public partial class PerfAnalysis : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Checkpoint[] checkpointsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        public Checkpoint[] Checkpoints {
            get {
                return this.checkpointsField;
            }
            set {
                this.checkpointsField = value;
                this.RaisePropertyChanged("Checkpoints");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.government-gateway.cz/wcf/submission")]
    public partial class GatewayAdditions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PerfAnalysis perfAnalysisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public PerfAnalysis PerfAnalysis {
            get {
                return this.perfAnalysisField;
            }
            set {
                this.perfAnalysisField = value;
                this.RaisePropertyChanged("PerfAnalysis");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.government-gateway.cz/wcf/submission")]
    public partial class Error : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime gatewayTimeStampField;
        
        private bool gatewayTimeStampFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string locationField;
        
        private int numberField;
        
        private bool numberFieldSpecified;
        
        private string raisedByField;
        
        private string textField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime GatewayTimeStamp {
            get {
                return this.gatewayTimeStampField;
            }
            set {
                this.gatewayTimeStampField = value;
                this.RaisePropertyChanged("GatewayTimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GatewayTimeStampSpecified {
            get {
                return this.gatewayTimeStampFieldSpecified;
            }
            set {
                this.gatewayTimeStampFieldSpecified = value;
                this.RaisePropertyChanged("GatewayTimeStampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberSpecified {
            get {
                return this.numberFieldSpecified;
            }
            set {
                this.numberFieldSpecified = value;
                this.RaisePropertyChanged("NumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string RaisedBy {
            get {
                return this.raisedByField;
            }
            set {
                this.raisedByField = value;
                this.RaisePropertyChanged("RaisedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.government-gateway.cz/wcf/submission")]
    public partial class GovTalkErrors : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        public Error[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.government-gateway.cz/wcf/submission")]
    public partial class PollResponseData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bodyBase64XMLField;
        
        private string classField;
        
        private string correlationIDField;
        
        private string functionField;
        
        private System.DateTime gatewayTimestampField;
        
        private bool gatewayTimestampFieldSpecified;
        
        private GovTalkErrors govTalkErrorsField;
        
        private string pollIntervalField;
        
        private string qualifierField;
        
        private GatewayAdditions gatewayAdditionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string BodyBase64XML {
            get {
                return this.bodyBase64XMLField;
            }
            set {
                this.bodyBase64XMLField = value;
                this.RaisePropertyChanged("BodyBase64XML");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
                this.RaisePropertyChanged("Class");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string CorrelationID {
            get {
                return this.correlationIDField;
            }
            set {
                this.correlationIDField = value;
                this.RaisePropertyChanged("CorrelationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Function {
            get {
                return this.functionField;
            }
            set {
                this.functionField = value;
                this.RaisePropertyChanged("Function");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime GatewayTimestamp {
            get {
                return this.gatewayTimestampField;
            }
            set {
                this.gatewayTimestampField = value;
                this.RaisePropertyChanged("GatewayTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GatewayTimestampSpecified {
            get {
                return this.gatewayTimestampFieldSpecified;
            }
            set {
                this.gatewayTimestampFieldSpecified = value;
                this.RaisePropertyChanged("GatewayTimestampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public GovTalkErrors GovTalkErrors {
            get {
                return this.govTalkErrorsField;
            }
            set {
                this.govTalkErrorsField = value;
                this.RaisePropertyChanged("GovTalkErrors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration", Order=6)]
        public string PollInterval {
            get {
                return this.pollIntervalField;
            }
            set {
                this.pollIntervalField = value;
                this.RaisePropertyChanged("PollInterval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string Qualifier {
            get {
                return this.qualifierField;
            }
            set {
                this.qualifierField = value;
                this.RaisePropertyChanged("Qualifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public GatewayAdditions GatewayAdditions {
            get {
                return this.gatewayAdditionsField;
            }
            set {
                this.gatewayAdditionsField = value;
                this.RaisePropertyChanged("GatewayAdditions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.government-gateway.cz/wcf/submission")]
    public partial class OptionalParameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string parameterNameField;
        
        private string parameterTypeField;
        
        private string parameterValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ParameterName {
            get {
                return this.parameterNameField;
            }
            set {
                this.parameterNameField = value;
                this.RaisePropertyChanged("ParameterName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ParameterType {
            get {
                return this.parameterTypeField;
            }
            set {
                this.parameterTypeField = value;
                this.RaisePropertyChanged("ParameterType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string ParameterValue {
            get {
                return this.parameterValueField;
            }
            set {
                this.parameterValueField = value;
                this.RaisePropertyChanged("ParameterValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.government-gateway.cz/wcf/submission")]
    public partial class BodyPart : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement bodyField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Xml.XmlElement Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("Body");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.government-gateway.cz/wcf/submission", ConfigurationName="SubmissionService.IBusinessTransactions")]
    public interface IBusinessTransactions {
        
        // CODEGEN: Parameter 'SubmitResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/Submit", ReplyAction="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/SubmitRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AutorizaceDigitalnihoUkonu.Web.SubmissionService.GGErrorException), Action="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/SubmitGGErr" +
            "orExceptionFault", Name="GGErrorException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutorizaceDigitalnihoUkonu.Web.SubmissionService.SubmitResponse Submit(AutorizaceDigitalnihoUkonu.Web.SubmissionService.SubmitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/Submit", ReplyAction="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/SubmitRespo" +
            "nse")]
        System.Threading.Tasks.Task<AutorizaceDigitalnihoUkonu.Web.SubmissionService.SubmitResponse> SubmitAsync(AutorizaceDigitalnihoUkonu.Web.SubmissionService.SubmitRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (MessageDetails) of message MessageDetails does not match the default value (SubmitLarge)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/SubmitLarge" +
            "", ReplyAction="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/SubmitLarge" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(AutorizaceDigitalnihoUkonu.Web.SubmissionService.GGErrorException), Action="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/SubmitLarge" +
            "GGErrorExceptionFault", Name="GGErrorException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollResponseMsg SubmitLarge(AutorizaceDigitalnihoUkonu.Web.SubmissionService.MessageDetails request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/SubmitLarge" +
            "", ReplyAction="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/SubmitLarge" +
            "Response")]
        System.Threading.Tasks.Task<AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollResponseMsg> SubmitLargeAsync(AutorizaceDigitalnihoUkonu.Web.SubmissionService.MessageDetails request);
        
        // CODEGEN: Parameter 'PollResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/Poll", ReplyAction="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/PollRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(AutorizaceDigitalnihoUkonu.Web.SubmissionService.GGErrorException), Action="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/PollGGError" +
            "ExceptionFault", Name="GGErrorException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollResponse Poll(AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/Poll", ReplyAction="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/PollRespons" +
            "e")]
        System.Threading.Tasks.Task<AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollResponse> PollAsync(AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollRequest request);
        
        // CODEGEN: Parameter 'correlationid' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/Dispose", ReplyAction="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/DisposeResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AutorizaceDigitalnihoUkonu.Web.SubmissionService.GGErrorException), Action="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/DisposeGGEr" +
            "rorExceptionFault", Name="GGErrorException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutorizaceDigitalnihoUkonu.Web.SubmissionService.DisposeResponse Dispose(AutorizaceDigitalnihoUkonu.Web.SubmissionService.DisposeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/Dispose", ReplyAction="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/DisposeResp" +
            "onse")]
        System.Threading.Tasks.Task<AutorizaceDigitalnihoUkonu.Web.SubmissionService.DisposeResponse> DisposeAsync(AutorizaceDigitalnihoUkonu.Web.SubmissionService.DisposeRequest request);
        
        // CODEGEN: Parameter 'DataRequestResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/DataRequest" +
            "", ReplyAction="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/DataRequest" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(AutorizaceDigitalnihoUkonu.Web.SubmissionService.GGErrorException), Action="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/DataRequest" +
            "GGErrorExceptionFault", Name="GGErrorException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutorizaceDigitalnihoUkonu.Web.SubmissionService.DataRequestResponse DataRequest(AutorizaceDigitalnihoUkonu.Web.SubmissionService.DataRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/DataRequest" +
            "", ReplyAction="http://www.government-gateway.cz/wcf/submission/IBusinessTransactions/DataRequest" +
            "Response")]
        System.Threading.Tasks.Task<AutorizaceDigitalnihoUkonu.Web.SubmissionService.DataRequestResponse> DataRequestAsync(AutorizaceDigitalnihoUkonu.Web.SubmissionService.DataRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Submit", WrapperNamespace="http://www.government-gateway.cz/wcf/submission", IsWrapped=true)]
    public partial class SubmitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.government-gateway.cz/wcf/submission", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tclass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.government-gateway.cz/wcf/submission", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public AutorizaceDigitalnihoUkonu.Web.SubmissionService.BodyPart[] bodies;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.government-gateway.cz/wcf/submission", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public AutorizaceDigitalnihoUkonu.Web.SubmissionService.OptionalParameter[] optionals;
        
        public SubmitRequest() {
        }
        
        public SubmitRequest(string tclass, AutorizaceDigitalnihoUkonu.Web.SubmissionService.BodyPart[] bodies, AutorizaceDigitalnihoUkonu.Web.SubmissionService.OptionalParameter[] optionals) {
            this.tclass = tclass;
            this.bodies = bodies;
            this.optionals = optionals;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitResponse", WrapperNamespace="http://www.government-gateway.cz/wcf/submission", IsWrapped=true)]
    public partial class SubmitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.government-gateway.cz/wcf/submission", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollResponseData SubmitResult;
        
        public SubmitResponse() {
        }
        
        public SubmitResponse(AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollResponseData SubmitResult) {
            this.SubmitResult = SubmitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MessageDetails", WrapperNamespace="http://www.government-gateway.cz/wcf/submission", IsWrapped=true)]
    public partial class MessageDetails {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.government-gateway.cz/wcf/submission")]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public AutorizaceDigitalnihoUkonu.Web.SubmissionService.OptionalParameter[] optionals;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.government-gateway.cz/wcf/submission")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tclass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.government-gateway.cz/wcf/submission", Order=0)]
        public System.IO.Stream Body;
        
        public MessageDetails() {
        }
        
        public MessageDetails(AutorizaceDigitalnihoUkonu.Web.SubmissionService.OptionalParameter[] optionals, string tclass, System.IO.Stream Body) {
            this.optionals = optionals;
            this.tclass = tclass;
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PollResponseMsg", WrapperNamespace="http://www.government-gateway.cz/wcf/submission", IsWrapped=true)]
    public partial class PollResponseMsg {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.government-gateway.cz/wcf/submission")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Class;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.government-gateway.cz/wcf/submission")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CorrelationID;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.government-gateway.cz/wcf/submission")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Function;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.government-gateway.cz/wcf/submission")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AutorizaceDigitalnihoUkonu.Web.SubmissionService.GatewayAdditions GatewayAdditions;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.government-gateway.cz/wcf/submission")]
        public System.DateTime GatewayTimestamp;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.government-gateway.cz/wcf/submission")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AutorizaceDigitalnihoUkonu.Web.SubmissionService.GovTalkErrors GovTalkErrors;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.government-gateway.cz/wcf/submission")]
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration")]
        public string PollInterval;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.government-gateway.cz/wcf/submission")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Qualifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.government-gateway.cz/wcf/submission", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BodyBase64XML;
        
        public PollResponseMsg() {
        }
        
        public PollResponseMsg(string Class, string CorrelationID, string Function, AutorizaceDigitalnihoUkonu.Web.SubmissionService.GatewayAdditions GatewayAdditions, System.DateTime GatewayTimestamp, AutorizaceDigitalnihoUkonu.Web.SubmissionService.GovTalkErrors GovTalkErrors, string PollInterval, string Qualifier, string BodyBase64XML) {
            this.Class = Class;
            this.CorrelationID = CorrelationID;
            this.Function = Function;
            this.GatewayAdditions = GatewayAdditions;
            this.GatewayTimestamp = GatewayTimestamp;
            this.GovTalkErrors = GovTalkErrors;
            this.PollInterval = PollInterval;
            this.Qualifier = Qualifier;
            this.BodyBase64XML = BodyBase64XML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Poll", WrapperNamespace="http://www.government-gateway.cz/wcf/submission", IsWrapped=true)]
    public partial class PollRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.government-gateway.cz/wcf/submission", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string correlationid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.government-gateway.cz/wcf/submission", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public AutorizaceDigitalnihoUkonu.Web.SubmissionService.OptionalParameter[] optionals;
        
        public PollRequest() {
        }
        
        public PollRequest(string correlationid, AutorizaceDigitalnihoUkonu.Web.SubmissionService.OptionalParameter[] optionals) {
            this.correlationid = correlationid;
            this.optionals = optionals;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PollResponse", WrapperNamespace="http://www.government-gateway.cz/wcf/submission", IsWrapped=true)]
    public partial class PollResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.government-gateway.cz/wcf/submission", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollResponseData PollResult;
        
        public PollResponse() {
        }
        
        public PollResponse(AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollResponseData PollResult) {
            this.PollResult = PollResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Dispose", WrapperNamespace="http://www.government-gateway.cz/wcf/submission", IsWrapped=true)]
    public partial class DisposeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.government-gateway.cz/wcf/submission", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string correlationid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.government-gateway.cz/wcf/submission", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public AutorizaceDigitalnihoUkonu.Web.SubmissionService.OptionalParameter[] optionals;
        
        public DisposeRequest() {
        }
        
        public DisposeRequest(string correlationid, AutorizaceDigitalnihoUkonu.Web.SubmissionService.OptionalParameter[] optionals) {
            this.correlationid = correlationid;
            this.optionals = optionals;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DisposeResponse", WrapperNamespace="http://www.government-gateway.cz/wcf/submission", IsWrapped=true)]
    public partial class DisposeResponse {
        
        public DisposeResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.government-gateway.cz/wcf/submission")]
    public partial class DataResponseBody : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime endTimeStampField;
        
        private bool endTimeStampFieldSpecified;
        
        private StatusRecord[] rowsField;
        
        private string senderIDField;
        
        private System.DateTime startTimeStampField;
        
        private bool startTimeStampFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime EndTimeStamp {
            get {
                return this.endTimeStampField;
            }
            set {
                this.endTimeStampField = value;
                this.RaisePropertyChanged("EndTimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndTimeStampSpecified {
            get {
                return this.endTimeStampFieldSpecified;
            }
            set {
                this.endTimeStampFieldSpecified = value;
                this.RaisePropertyChanged("EndTimeStampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        public StatusRecord[] Rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
                this.RaisePropertyChanged("Rows");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
                this.RaisePropertyChanged("SenderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime StartTimeStamp {
            get {
                return this.startTimeStampField;
            }
            set {
                this.startTimeStampField = value;
                this.RaisePropertyChanged("StartTimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartTimeStampSpecified {
            get {
                return this.startTimeStampFieldSpecified;
            }
            set {
                this.startTimeStampFieldSpecified = value;
                this.RaisePropertyChanged("StartTimeStampSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.government-gateway.cz/wcf/submission")]
    public partial class StatusRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string correlationIDField;
        
        private string statusField;
        
        private System.DateTime timeStampField;
        
        private bool timeStampFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string CorrelationID {
            get {
                return this.correlationIDField;
            }
            set {
                this.correlationIDField = value;
                this.RaisePropertyChanged("CorrelationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimeStampSpecified {
            get {
                return this.timeStampFieldSpecified;
            }
            set {
                this.timeStampFieldSpecified = value;
                this.RaisePropertyChanged("TimeStampSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataRequest", WrapperNamespace="http://www.government-gateway.cz/wcf/submission", IsWrapped=true)]
    public partial class DataRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.government-gateway.cz/wcf/submission", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tclass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.government-gateway.cz/wcf/submission", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public AutorizaceDigitalnihoUkonu.Web.SubmissionService.OptionalParameter[] optionals;
        
        public DataRequestRequest() {
        }
        
        public DataRequestRequest(string tclass, AutorizaceDigitalnihoUkonu.Web.SubmissionService.OptionalParameter[] optionals) {
            this.tclass = tclass;
            this.optionals = optionals;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataRequestResponse", WrapperNamespace="http://www.government-gateway.cz/wcf/submission", IsWrapped=true)]
    public partial class DataRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.government-gateway.cz/wcf/submission", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AutorizaceDigitalnihoUkonu.Web.SubmissionService.DataResponseBody DataRequestResult;
        
        public DataRequestResponse() {
        }
        
        public DataRequestResponse(AutorizaceDigitalnihoUkonu.Web.SubmissionService.DataResponseBody DataRequestResult) {
            this.DataRequestResult = DataRequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBusinessTransactionsChannel : AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusinessTransactionsClient : System.ServiceModel.ClientBase<AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions>, AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions {
        
        public BusinessTransactionsClient() {
        }
        
        public BusinessTransactionsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusinessTransactionsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessTransactionsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessTransactionsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutorizaceDigitalnihoUkonu.Web.SubmissionService.SubmitResponse AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions.Submit(AutorizaceDigitalnihoUkonu.Web.SubmissionService.SubmitRequest request) {
            return base.Channel.Submit(request);
        }
        
        public AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollResponseData Submit(string tclass, AutorizaceDigitalnihoUkonu.Web.SubmissionService.BodyPart[] bodies, AutorizaceDigitalnihoUkonu.Web.SubmissionService.OptionalParameter[] optionals) {
            AutorizaceDigitalnihoUkonu.Web.SubmissionService.SubmitRequest inValue = new AutorizaceDigitalnihoUkonu.Web.SubmissionService.SubmitRequest();
            inValue.tclass = tclass;
            inValue.bodies = bodies;
            inValue.optionals = optionals;
            AutorizaceDigitalnihoUkonu.Web.SubmissionService.SubmitResponse retVal = ((AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions)(this)).Submit(inValue);
            return retVal.SubmitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutorizaceDigitalnihoUkonu.Web.SubmissionService.SubmitResponse> AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions.SubmitAsync(AutorizaceDigitalnihoUkonu.Web.SubmissionService.SubmitRequest request) {
            return base.Channel.SubmitAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutorizaceDigitalnihoUkonu.Web.SubmissionService.SubmitResponse> SubmitAsync(string tclass, AutorizaceDigitalnihoUkonu.Web.SubmissionService.BodyPart[] bodies, AutorizaceDigitalnihoUkonu.Web.SubmissionService.OptionalParameter[] optionals) {
            AutorizaceDigitalnihoUkonu.Web.SubmissionService.SubmitRequest inValue = new AutorizaceDigitalnihoUkonu.Web.SubmissionService.SubmitRequest();
            inValue.tclass = tclass;
            inValue.bodies = bodies;
            inValue.optionals = optionals;
            return ((AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions)(this)).SubmitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollResponseMsg AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions.SubmitLarge(AutorizaceDigitalnihoUkonu.Web.SubmissionService.MessageDetails request) {
            return base.Channel.SubmitLarge(request);
        }
        
        public string SubmitLarge(AutorizaceDigitalnihoUkonu.Web.SubmissionService.OptionalParameter[] optionals, string tclass, System.IO.Stream Body, out string CorrelationID, out string Function, out AutorizaceDigitalnihoUkonu.Web.SubmissionService.GatewayAdditions GatewayAdditions, out System.DateTime GatewayTimestamp, out AutorizaceDigitalnihoUkonu.Web.SubmissionService.GovTalkErrors GovTalkErrors, out string PollInterval, out string Qualifier, out string BodyBase64XML) {
            AutorizaceDigitalnihoUkonu.Web.SubmissionService.MessageDetails inValue = new AutorizaceDigitalnihoUkonu.Web.SubmissionService.MessageDetails();
            inValue.optionals = optionals;
            inValue.tclass = tclass;
            inValue.Body = Body;
            AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollResponseMsg retVal = ((AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions)(this)).SubmitLarge(inValue);
            CorrelationID = retVal.CorrelationID;
            Function = retVal.Function;
            GatewayAdditions = retVal.GatewayAdditions;
            GatewayTimestamp = retVal.GatewayTimestamp;
            GovTalkErrors = retVal.GovTalkErrors;
            PollInterval = retVal.PollInterval;
            Qualifier = retVal.Qualifier;
            BodyBase64XML = retVal.BodyBase64XML;
            return retVal.Class;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollResponseMsg> AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions.SubmitLargeAsync(AutorizaceDigitalnihoUkonu.Web.SubmissionService.MessageDetails request) {
            return base.Channel.SubmitLargeAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollResponseMsg> SubmitLargeAsync(AutorizaceDigitalnihoUkonu.Web.SubmissionService.OptionalParameter[] optionals, string tclass, System.IO.Stream Body) {
            AutorizaceDigitalnihoUkonu.Web.SubmissionService.MessageDetails inValue = new AutorizaceDigitalnihoUkonu.Web.SubmissionService.MessageDetails();
            inValue.optionals = optionals;
            inValue.tclass = tclass;
            inValue.Body = Body;
            return ((AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions)(this)).SubmitLargeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollResponse AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions.Poll(AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollRequest request) {
            return base.Channel.Poll(request);
        }
        
        public AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollResponseData Poll(string correlationid, AutorizaceDigitalnihoUkonu.Web.SubmissionService.OptionalParameter[] optionals) {
            AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollRequest inValue = new AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollRequest();
            inValue.correlationid = correlationid;
            inValue.optionals = optionals;
            AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollResponse retVal = ((AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions)(this)).Poll(inValue);
            return retVal.PollResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollResponse> AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions.PollAsync(AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollRequest request) {
            return base.Channel.PollAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollResponse> PollAsync(string correlationid, AutorizaceDigitalnihoUkonu.Web.SubmissionService.OptionalParameter[] optionals) {
            AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollRequest inValue = new AutorizaceDigitalnihoUkonu.Web.SubmissionService.PollRequest();
            inValue.correlationid = correlationid;
            inValue.optionals = optionals;
            return ((AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions)(this)).PollAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutorizaceDigitalnihoUkonu.Web.SubmissionService.DisposeResponse AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions.Dispose(AutorizaceDigitalnihoUkonu.Web.SubmissionService.DisposeRequest request) {
            return base.Channel.Dispose(request);
        }
        
        public void Dispose(string correlationid, AutorizaceDigitalnihoUkonu.Web.SubmissionService.OptionalParameter[] optionals) {
            AutorizaceDigitalnihoUkonu.Web.SubmissionService.DisposeRequest inValue = new AutorizaceDigitalnihoUkonu.Web.SubmissionService.DisposeRequest();
            inValue.correlationid = correlationid;
            inValue.optionals = optionals;
            AutorizaceDigitalnihoUkonu.Web.SubmissionService.DisposeResponse retVal = ((AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions)(this)).Dispose(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutorizaceDigitalnihoUkonu.Web.SubmissionService.DisposeResponse> AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions.DisposeAsync(AutorizaceDigitalnihoUkonu.Web.SubmissionService.DisposeRequest request) {
            return base.Channel.DisposeAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutorizaceDigitalnihoUkonu.Web.SubmissionService.DisposeResponse> DisposeAsync(string correlationid, AutorizaceDigitalnihoUkonu.Web.SubmissionService.OptionalParameter[] optionals) {
            AutorizaceDigitalnihoUkonu.Web.SubmissionService.DisposeRequest inValue = new AutorizaceDigitalnihoUkonu.Web.SubmissionService.DisposeRequest();
            inValue.correlationid = correlationid;
            inValue.optionals = optionals;
            return ((AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions)(this)).DisposeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutorizaceDigitalnihoUkonu.Web.SubmissionService.DataRequestResponse AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions.DataRequest(AutorizaceDigitalnihoUkonu.Web.SubmissionService.DataRequestRequest request) {
            return base.Channel.DataRequest(request);
        }
        
        public AutorizaceDigitalnihoUkonu.Web.SubmissionService.DataResponseBody DataRequest(string tclass, AutorizaceDigitalnihoUkonu.Web.SubmissionService.OptionalParameter[] optionals) {
            AutorizaceDigitalnihoUkonu.Web.SubmissionService.DataRequestRequest inValue = new AutorizaceDigitalnihoUkonu.Web.SubmissionService.DataRequestRequest();
            inValue.tclass = tclass;
            inValue.optionals = optionals;
            AutorizaceDigitalnihoUkonu.Web.SubmissionService.DataRequestResponse retVal = ((AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions)(this)).DataRequest(inValue);
            return retVal.DataRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutorizaceDigitalnihoUkonu.Web.SubmissionService.DataRequestResponse> AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions.DataRequestAsync(AutorizaceDigitalnihoUkonu.Web.SubmissionService.DataRequestRequest request) {
            return base.Channel.DataRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutorizaceDigitalnihoUkonu.Web.SubmissionService.DataRequestResponse> DataRequestAsync(string tclass, AutorizaceDigitalnihoUkonu.Web.SubmissionService.OptionalParameter[] optionals) {
            AutorizaceDigitalnihoUkonu.Web.SubmissionService.DataRequestRequest inValue = new AutorizaceDigitalnihoUkonu.Web.SubmissionService.DataRequestRequest();
            inValue.tclass = tclass;
            inValue.optionals = optionals;
            return ((AutorizaceDigitalnihoUkonu.Web.SubmissionService.IBusinessTransactions)(this)).DataRequestAsync(inValue);
        }
    }
}
